name: dev-pipeline

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/dev-pipeline.yaml
      - 'user-svc/src/main/**'
      - 'user-svc/compose.yaml'
    branches:
      - dev

jobs:
  hello:
    name: hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: list
        run: |
          echo "Hello world"

  trivy_scan:
    name: Trivy Security Scan for Container Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to GitHub Container Registry (GHCR)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin

      - name: Pull and scan Docker images
        run: |
          # List of Docker images from compose.yaml
          IMAGES=(
            "docker.elastic.co/elasticsearch/elasticsearch:8.6.2"
            "docker.elastic.co/kibana/kibana:8.6.2"
            "docker.redpanda.com/redpandadata/console:latest"
            "confluentinc/cp-zookeeper:7.4.6"
            "confluentinc/cp-kafka:7.4.6"
          )
          
          # Install Trivy
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          
          # Iterate over each image and scan
          for IMAGE in "${IMAGES[@]}"; do
            echo "Pulling image: $IMAGE"
            docker pull "$IMAGE"
            
            echo "Scanning image: $IMAGE"
            ./trivy image "$IMAGE"
          done
