name: Python Application CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest  # Sử dụng Ubuntu để chạy workflow

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout mã nguồn từ repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Cài đặt Python
      with:
        python-version: '3.12'  # Đảm bảo cài đặt đúng phiên bản Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
      working-directory: ./email-verify-sender

    - name: Run the application
      run: |
        python main.py 
      working-directory: ./email-verify-sender
